### ISSUE TITLE
Just an example issue with a checklist

### ISSUE THREAD

**Issue by SvanBoxel** [SvanBoxel/actions-demo#49]
#### _Read these first!_  
**[How Solution Engineers Use GitHub](https://www.icloud.com/keynote/06-6dngfGgAMK168bBvYlAcYA#How_Solution_Engineers_use_GitHub)**   
[What, would you say, you do here?]( https://github.com/github/solutions-engineering/blob/master/README.md#what-we-do)  
[Guiding Principles for Technical Sales at GitHub](https://github.com/github/solutions-engineering/blob/master/guides/technical-selling-guiding-principles.md)

### Tools and Services: Essentials pt. 1
We use many different tools to get our jobs done on the SE team. Below are some of the tools you'll use every day, so make sure you set these up right away.

* [x] __[Okta](https://github.okta.com/)__ - Okta is a single sign-on tool that we use to provide GitHubbers access to Salesforce, AWS, GitHubberTV, BambooHR and others. Get an Okta account and set up two-factor authentication.

* [x] __[Slack](https://github.slack.com/)__ - Slack is the chat application we use at GitHub. Download the desktop or mobile client from your app store of choice, or sign in from Okta. Once you're set up, [gif](http://giphy.com/) and [emoji](http://emoji.muan.co/) to your :heart:'s content!
  * You'll want to join the [`#solutions-engineering`](https://github.slack.com/archives/solutions-engineering) room immediately, and there are a number of other useful rooms as well. Ask your buddy for good rooms to lurk in! (Hubot 👇 hangs out in [`#solutions-eng-info`](https://github.slack.com/archives/solutions-eng-info)
  * You may also want to start familiarizing yourself with Hubot
  ![image of Hubot](https://avatars2.githubusercontent.com/u/5367660?s=20).  More on his surly ways can be found [here](https://hubot.github.com/) and how we use him can be found in the [Using Hubot GitHubber article](https://githubber.com/article/tools/chat/using-hubot).

* [x] __[Halp](https://halp.githubapp.com)__ -  Halp is an internally-built ticketing system that we use to communicate with our customers. Customer-facing discussions about all sorts of topics happen here, from license requests to technical questions. Read more about Halp [here](https://github.com/github/sales/blob/master/guide/how-we-work.md#halp).

* [x] __[Salesforce.com](https://github.my.salesforce.com)__ - sign in to [Okta](http://github.okta.com/) and you should see Salesforce (SFDC) listed as a work application. Click the Salesforce icon to automatically sign in to Salesforce. You'll use your Okta credentials to access Salesforce. We use SFDC to manage the forecasting data around leads and opportunities (close date, amount, next steps).

* [ ] __[ghe.io](http://ghe.io/)__ - GitHub's own internal instance of GitHub Enterprise. We use ghe.io for internal team blogs. The Sales Weekly, Enablement Weekly, and a few other departments post their internal blogs to https://ghe.io to keep our team and the entire company updated on important announcements, the numbers, new customers, and notable deals. Access ghe.io through [Okta](https://github.okta.com/). 

* [x] __[Enterprise-Web](https://enterprise.github.com)__ - Sign in and authorize using the "GitHub" button, you should be staff. If not, please ask for help in the `#solutions-engineering`. From the customer's perspective, Enterprise Web is a portal where they can request a trial, download their license, access the latest release, and purchase seats. As GitHub staff, you'll have a CRM-esque view of our customers - trial requests, purchase history, custom agreement terms, and all active customer records are linked to Salesforce.
* [ ] __[Expensify](https://www.expensify.com/)__ - Expensify is used to track and submit expenses for reimbursement. The finance team has detailed articles on GitHubber on [what you can expense](https://githubber.com/article/benefits-and-policies/income/expenses) and [how to do it](https://githubber.com/article/benefits-and-policies/income/filing-an-expense-report). Access to this is available via [Okta](https://github.okta.com).

* [x] __[Team](https://team.githubapp.com)__ - Keep up to date with goings-on at GitHub.
  * Be sure that your team profile is filled out with first and last name as well as your bio mentioning what team you're on! This is important for people to know who you are and how to interact with you.

* [ ] __[GitHubber.com](https://githubber.com)__ - The essential guide to life at GitHub. This should be covered in general onboarding, but lots of competitive information also lives here for us!

* [ ] __[GitHubber.tv](https://githubber.tv)__ - All sorts of useful and interesting videos live here, including office hours and TL;DR recordings.

- [ ] __[Looker](https://looker.com/)__ is our business intelligence tool and provides all kinds of valuable data and analytics. Log in via Okta by clicking this [link to Okta](https://github.okta.com/app/UserHome) and click the Looker app.  You will receive an error message but in order to grant you access, you will need to attempt to log in first. We'll come back to Looker later!

- [ ] Hello world
